INSERT INTO "KYROLE_USER"("R_ID", "U_ID") VALUES ('3', '55');
INSERT INTO "KYROLE_USER"("R_ID", "U_ID") VALUES ('1', '1');
INSERT INTO "KYROLE_USER"("R_ID", "U_ID") VALUES ('4', '54');
INSERT INTO "KYROLE_USER"("R_ID", "U_ID") VALUES ('4', '36');
INSERT INTO "KYROLE_USER"("R_ID", "U_ID") VALUES ('3', '9');
